name: Theme Shadow CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: yarn install
    - name: VSCode Build
      run: yarn vs:pack
